# Generated by Django 4.0.3 on 2022-04-14 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("FullName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("Address", models.TextField()),
                ("Experience", models.FloatField()),
                ("Programming", models.CharField(max_length=100)),
                ("District", models.CharField(max_length=100)),
                ("State", models.CharField(max_length=100)),
                ("Country", models.CharField(max_length=100)),
                (
                    "Designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.designation",
                    ),
                ),
            ],
        ),
    ]
