# Generated by Django 4.0.4 on 2022-04-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_machinemark_facetoface_candidatestatus_aptitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='facetoface',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='machinemark',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
